/**
 * English strings for the reader surface. The dashboard keeps its own Hebrew
 * dictionary; no i18n framework — two flat dictionaries, one per surface.
 */
export const t = {
  brand: "NewsRadar",
  nav: {
    news: "News",
    monitoring: "Monitoring",
    frontPage: "Front page",
    sources: "Sources",
    interests: "Interests",
    digest: "Digest",
    share: "Share",
    archive: "Archive",
  },
  frontPage: {
    edition: (time: string) => `Edition ${time}`,
    refresh: "Refresh",
    refreshing: "Refreshing…",
    newEdition: "A newer edition is available",
    loadNewEdition: "Load it",
    stale: "This edition is more than 90 minutes old.",
    emptyTitle: "No edition yet",
    emptyBody:
      "Add sources and interests, then refresh to build your first edition.",
    emptyCta: "Go to Sources",
    sectionTop: "Top stories",
    coverageChip: (n: number) => `${n} sources`,
  },
  story: {
    originalHeading: (source: string) => `Original article — ${source}`,
    openOn: (source: string) => `Open on ${source}`,
    readFullOn: (source: string) => `Read the full article on ${source}`,
    frameBlockedNote:
      "This publisher does not allow embedding. Open the original to read it in full.",
    coverage: "Coverage",
    coverageIntro: "Every outlet that covered this story, oldest first.",
    backToFront: "Back to front page",
    byline: (name: string) => `By ${name}`,
    fullText: "Full article",
  },
  translation: {
    tag: (lang: string) => `Translated from ${lang}`,
    originalHeadline: "Original headline",
  },
  filters: {
    heading: "Filter",
    interests: "Interests",
    countries: "Countries",
    countryMode: "Country filter",
    publishedIn: "Published in",
    about: "About",
    publishedInHint: "Where the outlet is based",
    aboutHint: "What the story is about",
    window: "Time window",
    window6h: "6 hours",
    window24h: "24 hours",
    window3d: "3 days",
    clear: "Clear filters",
    apply: "Apply",
  },
  sources: {
    title: "Sources",
    tabMyFeeds: "My feeds",
    tabGlobal: "Global sources",
    pasteHeading: "Add sites in bulk",
    pastePlaceholder:
      "Paste up to 500 lines — bare domains or full URLs, one per line or comma-separated.",
    pasteSubmit: "Import sites",
    pasteImporting: "Importing…",
    discoverHeading: "Add a single site",
    discoverPlaceholder: "example.com",
    discoverSubmit: "Find feeds",
    discoverSubmitting: "Searching…",
    discoverNone: "No feeds found for that site.",
    subscribe: "Subscribe",
    opmlHeading: "Import OPML",
    opmlHint: "Drop an .opml file or choose one to import your existing subscriptions.",
    opmlChoose: "Choose OPML file",
    batchProgress: (done: number, total: number) => `${done} of ${total} processed`,
    copyFailed: "Copy failed lines",
    copied: "Copied",
    subsHeading: "Subscriptions",
    colTitle: "Title",
    colDomain: "Domain",
    colCountry: "Country",
    colTags: "Tags",
    colLastPoll: "Last poll",
    colFailures: "Failures",
    colRights: "Rights",
    colActive: "Active",
    rightsLinkOnly: "Headline + link",
    rightsExtract: "Short extract",
    rightsFull: "Full text (licensed)",
    rightsDialogTitle: "Change content rights",
    rightsWarning:
      "By selecting this you assert you have permission to store and display this content. This is a deliberate, logged decision.",
    rightsNoteLabel: "Justification (required)",
    rightsNotePlaceholder: "e.g. Licensing agreement signed 2026-01, ref #4821",
    rightsSave: "Save rights",
    rightsNoteMissing: "A justification note is required to upgrade rights.",
    globalHeading: "Global providers",
    globalEnabled: "Enabled",
    perigonUnavailable:
      "Perigon is unavailable — no API key is configured on the backend.",
    countryScope: "Country scope",
    langScope: "Language scope",
    reactivate: "Reactivate",
    autoDeactivated: "Auto-deactivated",
    failing: "Failing",
    bulkDeactivate: "Deactivate",
    bulkDelete: "Delete",
    bulkExport: "Export OPML",
    empty: "No sources yet. Paste some site URLs above to get started.",
  },
  interests: {
    title: "Interests",
    create: "New interest",
    name: "Name",
    description: "Description",
    descriptionHint:
      "Describe the interest in plain English — this drives semantic matching.",
    keywords: "Keywords",
    keywordsHint: "Press Enter to add a keyword.",
    publishedIn: "Published in (source countries)",
    about: "About (subject countries)",
    matchMode: "Country match mode",
    similarity: "Similarity threshold",
    similarityBroad: "Broad",
    similarityPrecise: "Precise",
    save: "Save interest",
    saving: "Saving…",
    previewHeading: "Live preview",
    previewHint: "The 5 most recent matches. Adjust the description or slider to calibrate.",
    previewEmpty: "No matches yet — broaden the description or lower the threshold.",
    previewNeedsSave: "Save the interest to see live matches.",
    delete: "Delete",
    empty: "No interests yet. Create one to shape your front page.",
  },
  digest: {
    title: "Digest",
    generate: "Generate now",
    generating: "Generating…",
    downloadPdf: "Download PDF",
    downloadMd: "Download Markdown",
    empty: "No digests yet. Generate one to see your headlines grouped by interest.",
    scheduleHeading: "Schedule",
    scheduleHour: "Hour (0–23)",
    scheduleTimezone: "Timezone",
    scheduleRecipients: "Recipients (comma-separated emails)",
    scheduleLookback: "Lookback (hours)",
    scheduleActive: "Active",
    scheduleSave: "Save schedule",
    generatedAt: (d: string) => `Generated ${d}`,
  },
  share: {
    title: "Share",
    create: "Create share link",
    scope: "Scope",
    scopeSite: "Whole site",
    scopeEdition: "This edition",
    scopeInterest: "One interest",
    scopeDigest: "Latest digest",
    label: "Label (optional)",
    expiry: "Expiry (optional)",
    copy: "Copy",
    copied: "Copied",
    revoke: "Revoke",
    revokeConfirm: "Revoke this link? Anyone holding it will lose access.",
    views: (n: number) => `${n} views`,
    revoked: "Revoked",
    expired: "Expired",
    active: "Active",
    feedsHeading: "Feed URLs",
    feedRss: "RSS",
    feedAtom: "Atom",
    feedJson: "JSON",
    empty: "No share links yet.",
  },
  publicView: {
    inactiveTitle: "This link is no longer active",
    inactiveBody: "The person who shared this may have revoked it or it has expired.",
  },
  states: {
    loading: "Loading…",
    errorTitle: "Something went wrong",
    retry: "Retry",
    empty: "Nothing here yet.",
  },
  a11y: {
    faviconAlt: (source: string) => `${source} favicon`,
    imageFallback: "No image available",
    keyboardHint: "j / k to move · Enter to open · o for source · / to filter",
  },
} as const;
