"""iOS backup keybag parsing, key derivation and AES key unwrap.

Implements the encrypted-backup key hierarchy used by iTunes/Finder backups
(iOS 10.2+ format). References the well-documented layout used by
iphone-dataprotection and Amnesty's MVT.

# TODO(verify-schema): validated against synthetic fixtures generated by this
# project (tests/fixtures helper). Cross-check WRAP flag semantics and the
# DPSL/DPIC double-protection derivation against a real iOS 15/16 backup
# before trusting on production evidence.
"""

from __future__ import annotations

import hashlib
import struct

from Crypto.Cipher import AES

# Protection-class WRAP flags.
WRAP_DEVICE = 1
WRAP_PASSCODE = 2

CLASSKEY_TAGS = ("CLAS", "WRAP", "WPKY", "KTYP", "PBKY")

# RFC 3394 default initial value.
_AES_KW_IV = 0xA6A6A6A6A6A6A6A6


class KeybagError(Exception):
    """Raised for keybag parsing / unlock failures."""


def _loop_tlv(blob: bytes):
    """Yield (tag, value) tuples from a keybag TLV blob."""
    i = 0
    n = len(blob)
    while i + 8 <= n:
        tag = blob[i : i + 4]
        length = struct.unpack(">I", blob[i + 4 : i + 8])[0]
        value = blob[i + 8 : i + 8 + length]
        yield tag.decode("ascii", "replace"), value
        i += 8 + length


def aes_unwrap_key(kek: bytes, wrapped: bytes) -> bytes:
    """RFC 3394 AES key unwrap. Returns the unwrapped key or raises."""
    if len(wrapped) % 8 != 0 or len(wrapped) < 24:
        raise KeybagError("invalid wrapped key length")
    n = len(wrapped) // 8 - 1
    a = struct.unpack(">Q", wrapped[:8])[0]
    r = [struct.unpack(">Q", wrapped[8 * (i + 1) : 8 * (i + 2)])[0] for i in range(n)]
    cipher = AES.new(kek, AES.MODE_ECB)
    for j in range(5, -1, -1):
        for i in range(n - 1, -1, -1):
            t = n * j + i + 1
            block = struct.pack(">QQ", a ^ t, r[i])
            b = cipher.decrypt(block)
            a = struct.unpack(">Q", b[:8])[0]
            r[i] = struct.unpack(">Q", b[8:])[0]
    if a != _AES_KW_IV:
        raise KeybagError("integrity check failed (wrong password?)")
    return b"".join(struct.pack(">Q", v) for v in r)


def aes_wrap_key(kek: bytes, plaintext: bytes) -> bytes:
    """RFC 3394 AES key wrap (used only to build test fixtures)."""
    if len(plaintext) % 8 != 0:
        raise KeybagError("plaintext must be a multiple of 8 bytes")
    n = len(plaintext) // 8
    a = _AES_KW_IV
    r = [struct.unpack(">Q", plaintext[8 * i : 8 * i + 8])[0] for i in range(n)]
    cipher = AES.new(kek, AES.MODE_ECB)
    for j in range(6):
        for i in range(n):
            block = struct.pack(">QQ", a, r[i])
            b = cipher.encrypt(block)
            a = struct.unpack(">Q", b[:8])[0] ^ (n * j + i + 1)
            r[i] = struct.unpack(">Q", b[8:])[0]
    return struct.pack(">Q", a) + b"".join(struct.pack(">Q", v) for v in r)


class Keybag:
    """A parsed backup keybag capable of unlocking protection-class keys."""

    def __init__(self, data: bytes) -> None:
        self.type: int | None = None
        self.uuid: bytes | None = None
        self.wrap: int | None = None
        self.attrs: dict[str, bytes | int] = {}
        self.class_keys: dict[int, dict[str, bytes | int]] = {}
        self._unlocked = False
        self._parse(data)

    def _parse(self, data: bytes) -> None:
        current: dict[str, bytes | int] | None = None
        for tag, value in _loop_tlv(data):
            ival = struct.unpack(">I", value)[0] if len(value) == 4 else value
            if tag == "TYPE":
                self.type = ival if isinstance(ival, int) else None
            elif tag == "UUID" and self.uuid is None:
                self.uuid = value
            elif tag == "WRAP" and self.wrap is None:
                self.wrap = ival if isinstance(ival, int) else None
            elif tag == "UUID":
                if current is not None and "CLAS" in current:
                    self.class_keys[int(current["CLAS"])] = current
                current = {"UUID": value}
            elif tag in CLASSKEY_TAGS:
                if current is None:
                    current = {}
                current[tag] = ival
            else:
                self.attrs[tag] = ival
        if current is not None and "CLAS" in current:
            self.class_keys[int(current["CLAS"])] = current

    def unlock_with_password(self, password: str) -> None:
        """Derive the passcode key and unwrap all passcode-wrapped class keys."""
        for required in ("SALT", "ITER", "DPSL", "DPIC"):
            if required not in self.attrs:
                raise KeybagError(f"keybag missing {required}; not an encrypted backup keybag")
        pw = password.encode("utf-8")
        stage1 = hashlib.pbkdf2_hmac("sha256", pw, self.attrs["DPSL"], int(self.attrs["DPIC"]), 32)
        passcode_key = hashlib.pbkdf2_hmac(
            "sha1", stage1, self.attrs["SALT"], int(self.attrs["ITER"]), 32
        )
        unlocked_any = False
        for ck in self.class_keys.values():
            if "WPKY" not in ck:
                continue
            if int(ck.get("WRAP", 0)) & WRAP_PASSCODE:
                ck["KEY"] = aes_unwrap_key(passcode_key, ck["WPKY"])
                unlocked_any = True
        if not unlocked_any:
            raise KeybagError("no passcode-wrapped class keys unlocked (wrong password?)")
        self._unlocked = True

    def unwrap_file_key(self, protection_class: int, wrapped_key: bytes) -> bytes:
        """Unwrap a per-file key using the given protection class key."""
        if not self._unlocked:
            raise KeybagError("keybag is locked; call unlock_with_password first")
        ck = self.class_keys.get(protection_class)
        if ck is None or "KEY" not in ck:
            raise KeybagError(f"protection class {protection_class} not available")
        return aes_unwrap_key(ck["KEY"], wrapped_key)


def decrypt_cbc(key: bytes, data: bytes, unpad: bool = True) -> bytes:
    """AES-CBC decrypt with a zero IV (iOS file encryption). Optionally unpad."""
    cipher = AES.new(key, AES.MODE_CBC, iv=b"\x00" * 16)
    out = cipher.decrypt(data)
    if unpad:
        pad = out[-1]
        if 1 <= pad <= 16 and out[-pad:] == bytes([pad]) * pad:
            out = out[:-pad]
    return out


def encrypt_cbc(key: bytes, data: bytes) -> bytes:
    """AES-CBC encrypt with a zero IV and PKCS7 padding (fixtures only)."""
    pad = 16 - (len(data) % 16)
    data = data + bytes([pad]) * pad
    cipher = AES.new(key, AES.MODE_CBC, iv=b"\x00" * 16)
    return cipher.encrypt(data)
