"""add training_image

Revision ID: 922c5b962f74
Revises: b4ef596ed14f
Create Date: 2026-06-21 08:25:22.770225
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # referenced by JSONB astext_type in rendered columns
import app.models.base  # portable GUID type referenced by autogenerated columns


revision: str = '922c5b962f74'
down_revision: Union[str, None] = 'b4ef596ed14f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_image',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('persona_id', app.models.base.GUID(), nullable=False),
    sa.Column('storage_uri', sa.String(length=512), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_image')
    # ### end Alembic commands ###
