"""initial schema

Revision ID: b4ef596ed14f
Revises: 
Create Date: 2026-06-03 15:59:27.674287
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text  # referenced by JSONB astext_type in rendered columns
import app.models.base  # portable GUID type used by the models

revision: str = 'b4ef596ed14f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('responsible_entity',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('contact_email', sa.String(length=320), nullable=False),
    sa.Column('jurisdiction', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persona',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('backstory', sa.Text(), nullable=True),
    sa.Column('voice_tone', sa.Text(), nullable=True),
    sa.Column('values', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('hard_boundaries', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('visual_identity', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('responsible_entity_id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['responsible_entity_id'], ['responsible_entity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('persona_id', app.models.base.GUID(), nullable=False),
    sa.Column('kind', sa.Enum('IMAGE', 'VIDEO', 'TEXT', name='assetkind'), nullable=False),
    sa.Column('storage_uri', sa.String(length=512), nullable=True),
    sa.Column('provenance_manifest_uri', sa.String(length=512), nullable=True),
    sa.Column('provenance_manifest', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('disclosure_status', sa.Enum('PENDING', 'TAGGED', 'BLOCKED', name='disclosurestatus'), nullable=False),
    sa.Column('prompt', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lora_model',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('persona_id', app.models.base.GUID(), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('base_model', sa.String(length=120), nullable=False),
    sa.Column('training_meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('weights_uri', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('persona_id', app.models.base.GUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('audience', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('content_pillars', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('tone', sa.String(length=400), nullable=True),
    sa.Column('recommended_platforms', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('themes', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('synthetic_identity',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('persona_id', app.models.base.GUID(), nullable=False),
    sa.Column('responsible_entity_id', app.models.base.GUID(), nullable=False),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('ai_generated', name='ck_synthetic_identity_ai_generated'),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsible_entity_id'], ['responsible_entity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('persona_id')
    )
    op.create_table('post',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('asset_id', app.models.base.GUID(), nullable=False),
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('caption', sa.String(length=2200), nullable=True),
    sa.Column('approval_state', sa.Enum('DRAFT', 'APPROVED', 'PUBLISHED', 'REJECTED', 'FAILED', name='approvalstate'), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_post_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analytics_event',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('persona_id', app.models.base.GUID(), nullable=False),
    sa.Column('post_id', app.models.base.GUID(), nullable=True),
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('metric', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analytics_event')
    op.drop_table('post')
    op.drop_table('synthetic_identity')
    op.drop_table('strategy')
    op.drop_table('lora_model')
    op.drop_table('asset')
    op.drop_table('persona')
    op.drop_table('responsible_entity')
    # ### end Alembic commands ###
