"""Forensic report generator for a campaign or narrative.

Produces a structured report (exec summary via the AI provider, timeline, top
accounts, evidence quotes, recommendations) and renders it to standalone HTML.
"""
from __future__ import annotations

import html

from sqlalchemy import select
from sqlalchemy.orm import Session

from ..ai import get_provider
from ..models import (
    Author, Campaign, CampaignEvidence, Narrative, Post,
)


def _recommendations(kind: str, score: float) -> list[str]:
    recs = ["Preserve the evidence posts and account snapshots for the record."]
    if score >= 66:
        recs += [
            "Escalate: report the coordinated accounts to the platform(s).",
            "Prepare a public clarification if the narrative targets your entity.",
        ]
    elif score >= 40:
        recs.append("Monitor for further amplification before acting.")
    else:
        recs.append("Low signal — keep under observation.")
    return recs


def build_campaign_report(db: Session, campaign_id: int) -> dict | None:
    c = db.get(Campaign, campaign_id)
    if not c:
        return None
    accounts = []
    for ca in c.accounts:
        a = db.get(Author, ca.author_id)
        if a:
            accounts.append({"handle": a.handle or a.display_name, "source": a.source,
                             "authenticity_score": a.authenticity_score})
    evidence = []
    for ev in db.scalars(select(CampaignEvidence).where(CampaignEvidence.campaign_id == c.id)):
        p = db.get(Post, ev.post_id)
        if p:
            evidence.append({"source": p.source, "text": p.text, "url": p.url, "timestamp": p.timestamp})
    summary = get_provider().summarize([e["text"] for e in evidence],
                                       context="Coordinated campaign:")
    return {
        "kind": "campaign", "id": c.id, "title": f"Coordinated Campaign #{c.id}",
        "score_label": "Coordination score", "score": c.coordination_score,
        "meta": {"accounts": c.account_count, "posts": c.post_count,
                 "sources": c.sources, "time_start": c.time_start, "time_end": c.time_end},
        "summary": summary, "accounts": accounts, "evidence": evidence,
        "recommendations": _recommendations("campaign", c.coordination_score),
    }


def build_narrative_report(db: Session, narrative_id: int) -> dict | None:
    n = db.get(Narrative, narrative_id)
    if not n:
        return None
    posts = list(db.scalars(select(Post).where(Post.narrative_id == n.id).limit(50)))
    evidence = [{"source": p.source, "text": p.text, "url": p.url, "timestamp": p.timestamp} for p in posts[:10]]
    return {
        "kind": "narrative", "id": n.id, "title": f"Narrative: {n.label}",
        "score_label": "Manipulation index", "score": n.manipulation_index or 0,
        "meta": {"posts": n.post_count, "accounts": n.account_count,
                 "sentiment_avg": n.sentiment_avg, "keywords": n.keywords},
        "summary": n.summary or get_provider().summarize([p.text for p in posts]),
        "accounts": [], "evidence": evidence,
        "recommendations": _recommendations("narrative", n.manipulation_index or 0),
    }


def render_html(report: dict) -> str:
    e = html.escape
    meta_rows = "".join(
        f"<tr><td>{e(str(k))}</td><td>{e(str(v))}</td></tr>" for k, v in report["meta"].items()
    )
    accounts = "".join(
        f"<li>{e(str(a['handle']))} <small>({e(str(a['source']))}, authenticity "
        f"{e(str(a['authenticity_score']))})</small></li>" for a in report["accounts"]
    )
    evidence = "".join(
        f"<blockquote>{e(v['text'])}<br><small>{e(str(v['source']))} · {e(str(v['timestamp']))}</small></blockquote>"
        for v in report["evidence"]
    )
    recs = "".join(f"<li>{e(r)}</li>" for r in report["recommendations"])
    return f"""<!doctype html><html><head><meta charset="utf-8">
<title>{e(report['title'])}</title>
<style>body{{font-family:system-ui,Arial,sans-serif;max-width:820px;margin:2rem auto;padding:0 1rem;color:#111}}
h1{{margin-bottom:.2rem}} .score{{font-size:1.5rem;font-weight:700}}
table{{border-collapse:collapse;margin:1rem 0}} td{{border:1px solid #ddd;padding:.3rem .6rem}}
blockquote{{border-left:3px solid #ccc;margin:.5rem 0;padding:.3rem .8rem;color:#333;background:#fafafa}}
small{{color:#666}}</style></head><body>
<h1>{e(report['title'])}</h1>
<div class="score">{e(report['score_label'])}: {e(str(report['score']))}/100</div>
<h2>Executive summary</h2><p>{e(report['summary'])}</p>
<h2>Details</h2><table>{meta_rows}</table>
{'<h2>Accounts</h2><ul>' + accounts + '</ul>' if accounts else ''}
<h2>Evidence</h2>{evidence or '<p>No evidence captured.</p>'}
<h2>Recommended actions</h2><ul>{recs}</ul>
<hr><small>Generated by narrative-intel. Indicators with evidence — not a verdict.</small>
</body></html>"""
